import type { Metadata } from "next";

import "@/app/styles/globals.css";
import "@/app/styles/style.css";
import { quicksand } from "@/fonts";
import NextAuthWrapper from "@/lib/next_auth.wrapper";
import { ReactQueryProvider } from "@/context/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-full h-full overflow-auto`}
        style={{ fontFamily: quicksand.style.fontFamily }}
      >
        <NextAuthWrapper>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
