import type { Metadata } from "next";

import "@/app/styles/globals.css";
import "@/app/styles/style.css";
import AppHeader from "@/components/layouts/header/App_header";
import AppFooter from "@/components/layouts/footer/App_footer";
import { quicksand } from "@/fonts";
import Sidebar from "@/components/layouts/sidebar/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-full h-full overflow-auto`}
        style={{ fontFamily: quicksand.style.fontFamily }}
      >
        <SidebarProvider>
          <div className="absolute">
            <Sidebar />
          </div>
          <div className="relative ml-0 transition-all duration-300">
            {/* Nội dung của bạn sẽ di chuyển sang bên phải khi sidebar mở */}
            <AppHeader />
            {children}
            <AppFooter />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
